# Generated by Django 4.2.16 on 2025-01-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="User Name")),
                ("email", models.EmailField(max_length=20, verbose_name="User Email")),
                ("mobile", models.PositiveIntegerField(verbose_name="User Number")),
                ("password", models.CharField(max_length=20, verbose_name="Password")),
            ],
        ),
    ]
