# Generated by Django 4.2.16 on 2025-01-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="email",
            field=models.EmailField(max_length=100, verbose_name="User Email"),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=50, verbose_name="User Name"),
        ),
        migrations.AlterField(
            model_name="item",
            name="password",
            field=models.CharField(max_length=50, verbose_name="Password"),
        ),
    ]
