# Generated by Django 4.2.16 on 2025-01-11 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_item_email_alter_item_name_alter_item_password"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item", old_name="name", new_name="username",
        ),
    ]
