# Generated by Django 4.2.16 on 2025-01-13 12:00

import Page.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                ("author", models.CharField(max_length=50, verbose_name="Author")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Price"
                    ),
                ),
                (
                    "date_added",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Date Added"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=50, verbose_name="Subject")),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Full Name")),
                (
                    "mobile",
                    models.CharField(max_length=10, verbose_name="Mobile Number"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email Address"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="Password")),
                (
                    "address",
                    models.TextField(default="Default Address", verbose_name="Address"),
                ),
                (
                    "birthdate",
                    models.DateField(
                        default=datetime.date(2000, 1, 1), verbose_name="Date of Birth"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stuff",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, verbose_name="Full Name")),
                (
                    "mobile",
                    models.CharField(max_length=10, verbose_name="Mobile Number"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email Address"
                    ),
                ),
                ("crn", models.CharField(max_length=10, verbose_name="CRN")),
                ("password", models.CharField(max_length=128, verbose_name="Password")),
            ],
        ),
        migrations.CreateModel(
            name="IssueBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "charges",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Per Day Charges"
                    ),
                ),
                ("issue_date", models.DateField()),
                ("end_date", models.DateField()),
                ("issue_time", models.TimeField(default=Page.models.current_time)),
                (
                    "typeOf_issue",
                    models.CharField(
                        default="select", max_length=100, verbose_name="Type of Issue"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Page.book",
                        verbose_name="Issue Books",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Page.stuff",
                        verbose_name="Staff",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Page.person",
                        verbose_name="Student Name",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookReturned",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_charges",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Total Charges"
                    ),
                ),
                ("issue_date", models.DateField()),
                ("returned_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        default="Pending", max_length=100, verbose_name="Status"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Page.book",
                        verbose_name="Issue Books",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Page.stuff",
                        verbose_name="Staff",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Page.person",
                        verbose_name="Student Name",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Page.category",
                verbose_name="Category",
            ),
        ),
    ]
