# Generated by Django 4.2.16 on 2024-11-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Page", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="password",
            field=models.CharField(default="vipinspawarp@gmail.com", max_length=10),
            preserve_default=False,
        ),
    ]
