# Generated by Django 4.2.16 on 2024-11-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Page", "0002_person_email_person_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="mobile",
            field=models.CharField(default=725495445, max_length=10),
        ),
        migrations.AddField(
            model_name="person",
            name="name",
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="person",
            name="password",
            field=models.CharField(default=0, max_length=10),
        ),
    ]
