# Generated by Django 4.2.16 on 2024-11-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Page", "0003_person_mobile_person_name_alter_person_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="mobile",
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="person",
            name="password",
            field=models.CharField(default=True, max_length=10),
        ),
    ]
