# Generated by Django 4.2.16 on 2024-11-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Page", "0004_alter_person_mobile_alter_person_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person", name="email", field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="person", name="mobile", field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="person", name="name", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="person", name="password", field=models.CharField(max_length=10),
        ),
    ]
