# Generated by Django 4.2.16 on 2024-12-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Page", "0005_alter_person_email_alter_person_mobile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Email Address"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="mobile",
            field=models.CharField(max_length=10, verbose_name="Mobile Number"),
        ),
        migrations.AlterField(
            model_name="person",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Full Name"),
        ),
        migrations.AlterField(
            model_name="person",
            name="password",
            field=models.CharField(max_length=128, verbose_name="Password"),
        ),
    ]
