# Generated by Django 4.2.16 on 2024-12-21 06:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Page", "0006_alter_person_email_alter_person_mobile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(max_length=50, verbose_name="Category Name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
                ("author", models.CharField(max_length=50, verbose_name="Author")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Price"
                    ),
                ),
                (
                    "date_added",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Date Added"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Page.category",
                        verbose_name="Category",
                    ),
                ),
            ],
        ),
    ]
