# Generated by Django 4.2.16 on 2024-12-21 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Page", "0008_book_delete_books"),
    ]

    operations = [
        migrations.RemoveField(model_name="book", name="quantity",),
    ]
