# Generated by Django 4.2.16 on 2024-12-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Page", "0009_remove_book_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Price"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="category",
            name="subject",
            field=models.CharField(max_length=50, verbose_name="Subject"),
        ),
    ]
