# Generated by Django 4.2.16 on 2024-12-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Page", "0010_alter_book_price_alter_book_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
