# Generated by Django 4.2.16 on 2024-12-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Page", "0011_alter_book_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stuff",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, verbose_name="Full Name")),
                (
                    "mobile",
                    models.CharField(max_length=10, verbose_name="Mobile Number"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email Address"
                    ),
                ),
                ("crn", models.CharField(max_length=10, verbose_name="CRN")),
                ("password", models.CharField(max_length=128, verbose_name="Password")),
            ],
        ),
    ]
