# Generated by Django 4.2.16 on 2024-12-24 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Page", "0012_stuff"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="address",
            field=models.TextField(default="Default Address", verbose_name="Address"),
        ),
        migrations.AddField(
            model_name="person",
            name="birthdate",
            field=models.DateField(
                default=datetime.date(2000, 1, 1), verbose_name="Date of Birth"
            ),
        ),
    ]
