# Generated by Django 4.2.16 on 2024-12-26 05:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Page", "0013_person_address_person_birthdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "charges",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Per Day Charges"
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Issue Date"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Return Date"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Page.book",
                        verbose_name="Issue Books",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Page.stuff",
                        verbose_name="Staff",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Page.person",
                        verbose_name="Student Name",
                    ),
                ),
            ],
        ),
    ]
