# Generated by Django 4.2.16 on 2024-12-30 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Page", "0014_issuebook"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuebook", name="end_date", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="issuebook", name="issue_date", field=models.DateField(),
        ),
        migrations.CreateModel(
            name="BookReturned",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_charges",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Per Day Charges"
                    ),
                ),
                ("issue_date", models.DateField()),
                ("returned_date", models.DateField()),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Page.book",
                        verbose_name="Issue Books",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Page.stuff",
                        verbose_name="Staff",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Page.person",
                        verbose_name="Student Name",
                    ),
                ),
            ],
        ),
    ]
