# Generated by Django 4.2.16 on 2024-12-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Page", "0015_alter_issuebook_end_date_alter_issuebook_issue_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookreturned",
            name="status",
            field=models.CharField(
                default="Pending", max_length=100, verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="bookreturned",
            name="total_charges",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Total Charges"
            ),
        ),
    ]
