# Generated by Django 4.2.16 on 2024-12-31 13:55

import Page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Page", "0016_bookreturned_status_alter_bookreturned_total_charges"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuebook",
            name="issue_time",
            field=models.TimeField(default=Page.models.current_time),
        ),
    ]
