from django.urls import path
from Page import views


urlpatterns = [
        # path('edit-person/<int:person_id>/', views.edit_data,name="edit_data"),
    path("", views.index, name='index'),
    path("signin/", views.person, name='person'),
    path("send_data/", views.send_data, name='send_data'),
    path("persondata/", views.persondata, name='persondata'),
    path("delete/<int:person_id>/", views.delete_data,name="delete_data"),
    path("update-person/", views.update_data, name="update_data"),
    path('show-date/', views.show_date, name='show_date'),
    path('show-time/', views.show_time, name='show_time'),
    path('login/', views.login_view, name='login'),
    path('person-detail/<int:pid>/', views.person_view, name='persons'),
    path('logout/', views.logout_view, name='logout'),
    path("header/", views.HeaderView.as_view(), name='header'),
    path("sidebar/", views.SidebarView.as_view(), name='sidebar'),
    # path("", views.BaseView.as_view(), name='base'),
    path("person-table/", views.person_table,name='person-table'),
    path("login-page/", views.login_page,name='login-page'),
    path("forget-page/", views.forget_page, name='forget-page'),
    path('reset/',views.send_otp,name= 'reset'),
    path('verify/', views.verify_otp, name='verify_otp'),
    path('set-pass/', views.set_pass, name='set_pass'),
    path('books/', views.all_books,name='books'),
    path('category/', views.all_category,name='category'),
    path('stuff/', views.stuff, name='stuff'),
    path('update-stuff/', views.update_stuff, name='update_stuff'),
    path('delete-stuff/', views.delete_stuff, name='delete_stuff'),
    path('add-stuff/', views.add_stuff, name='add_stuff'),
    path('issue-book/', views.issue_book, name='issue_book'),
    path('add-book/', views.add_book, name='add_book'),
    path('edit-book/', views.edit_book, name='edit_book'),
    path('delete-book/', views.delete_book, name='delete_book'),
    path('add_category/', views.add_category, name='add_category'),
    path('delete_category/', views.delete_category, name='delete_category'),
    path('edit_category/', views.edit_category, name='edit_category'),
    path('add-student/', views.add_student, name='add_student'),
    path('add-staff/', views.add_staff, name='add_staff'),
    path('edit-staff/<int:id>/', views.edit_staff, name='edit_staff'),
    path('edit-student/<int:id>/', views.edit_student, name='edit_student'),
    path('issue-table/', views.issue_table, name="issue_table"),
    path('save_issuedbook/', views.save_issuedbook, name="save_issuedbook"),
    path('delete_issuedbook/<int:id>/', views.delete_issuedbook, name='delete_issuedbook'),
    path('return_status/', views.return_status, name='return_status'),
    path('returnbook-page/', views.returnbook_page, name = 'returnbook_page'),
    path('edit-issuedbook/<int:id>/', views.edit_issuedbook, name='edit_issuedbook'),
    path('update-issuedbook/', views.update_issuedbook, name='update_issuedbook'),

]
